micronaut:
  application:
    name: mnStockBroker
  server:
    port: 9080
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: secretManagerFromCloudProviderSearchForThat