micronaut:
  application:
    name: mnStockBroker
  server:
    port: 9080
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: secretManagerFromCloudProviderSearchForThat
datasources:
  default:
    url: ${PG_JDBC_URL:`jdbc:postgresql://127.0.0.1:5432/mn-stock-broker`}
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD} # admin8780
    driver-class-name: org.postgresql.Driver
    schema-genenerate: NONE
    dialect: POSTGRES
# micronaut-data-jpa
jpa:
  default:
    packages-to-scan:
      - "com.micronaut.udemy.broker.persistence"
    properties:
      hibernate:
        show_sql: false
liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'